requires 'Algorithm::BinPack::2D';
requires 'File::Slurper';
requires 'Function::Parameters';
requires 'Game::DijkstraMap', '>= 1.01';
requires 'Game::LevelMap';
requires 'Game::PseudoRand';
requires 'Game::TextPatterns', '>= 0.73';
requires 'Imager';
requires 'List::Util';
requires 'List::UtilsBy';
requires 'Math::Trig';
requires 'Queue::Priority';
requires 'Types::Standard';
