requires 'Algorithm::BinPack::2D';
requires 'Class::MOP';
requires 'File::Slurper';
requires 'Function::Parameters';
requires 'Game::DijkstraMap', '>= 1.01';
requires 'Game::LevelMap';
requires 'Game::PseudoRand';
requires 'Game::RaycastFOV';
requires 'Game::TextPatterns', '>= 1.46';
requires 'Imager';
requires 'JSON::MaybeXS';
requires 'List::Util';
requires 'List::UtilsBy';
requires 'Math::Random::Discrete';
requires 'Math::Trig';
requires 'Moo';
requires 'Queue::Priority';
requires 'Types::Standard';
requires 'Variable::Magic';
