#!/usr/bin/env perl
# combines maps as columns (a horizontal cat, so to speak)
# see Game::TextPatterns for how to use the @fill, e.g.
#   --fill x --fill y
# to handle the two different cases
use 5.24.0;
use warnings;
use File::Slurper qw(read_text);
use Game::TextPatterns;
use Getopt::Long qw(GetOptions);
GetOptions( 'fill=s' => \my @fill ) or exit 1;
$fill[0] = '?' unless @fill;
die "Usage: gtp-appendcols file1 file2 [..]\n" unless @ARGV > 1;
my @pats = map { Game::TextPatterns->new( pattern => read_text $_ ) } @ARGV;
my $first = shift @pats;
$first->append_cols( \@fill, $_ ) for @pats;
print $first->string;
